defaults:
  - _self_

text_encoder_cfg:
  encoder: bert-base-uncased
  lora: true
  input_dim: 768     # BERT's hidden size
  output_dim: 768
  freeze: false

vision_encoder_cfg:
  encoder: swin_base_patch4_window7_224
  lora: false
  input_dim: 768     # ViT's patch embedding size
  output_dim: 1000
  freeze: false

fusion_cfg:
  fusion_type: concat
  input_dim: 768      # Optional: only used if projecting embeddings after concat
  output_dim: 768

decoder_cfg:
  decoder: facebook/bart-base
  lora: true
  input_dim: 768      # Match fusion output_dim
  hidden_dim: 768
  output_dim: 768
  freeze: false

trainer:
  precision: 32
  accelerator: auto
  devices: 1
  batch_size: 32
  lr: 1e-5
  device: cuda
  epochs: 90
  output_dir: /home/hov1syv/Desktop/Personal/research/video-commentary-ai/checkpoints
  max_seq_length: 128
  mlm_probability: 0.15
  save_steps: 500
  logging_steps: 100

data:
  captions_dir: /home/hov1syv/Desktop/Personal/research/video-commentary-ai/captions_csv
  frames_dir: /home/hov1syv/Desktop/Personal/research/video-commentary-ai/frames
  audio_dir: /home/hov1syv/Desktop/Personal/research/video-commentary-ai/mfccs
  batch_size: 32
  num_workers: 4
  pin_memory: false
  use_csv: True

inference:
  batch_size: 1
  num_workers: 0
  pin_memory: false
  max_length: 128
  top_k: 50
  top_p: 0.95
  temperature: 1.0
  image_size: 224
  num_beams: 5
  image_dir: /home/hov1syv/Desktop/Personal/research/video-commentary-ai/frames/How To Insert A Nasogastric Tube » NG Tube » Nursing Skills_clip_40.0s_to_183.0s
  output_dir: /home/hov1syv/Desktop/Personal/research/video-commentary-ai/eval_results
  num_samples: 40
  captions_csv: /home/hov1syv/Desktop/Personal/research/video-commentary-ai/captions_csv/How To Insert A Nasogastric Tube » NG Tube » Nursing Skills_clip_40.0s_to_183.0s.csv